Repository codetriage/CodeTriage, pull requests merged in 2022-10, with the labels that each got.

#1683 Add Support for Storing Repo Labels
  app/models/label.rb
  app/models/repo.rb
  app/models/repo_label.rb
  app/services/repo_label_assigner.rb
  db/migrate/20221004010742_create_labels_table.rb
  db/migrate/20221004010749_create_repo_labels_table.rb
  db/schema.rb
  lib/tasks/schedule.rake
  test/unit/repo_labels_assigner_test.rb
  test/vcr_cassettes/fetch_labels_for_repo.yml
Labels: hacktoberfest

#1687 upgrade dependencies
  Gemfile.lock
Labels: dependencies, hacktoberfest-accepted

#1705 Upgrade Ruby to 3.1.2
  Gemfile
  Gemfile.lock
  test/test_helper.rb
Labels: hacktoberfest-accepted

#1707 Update Rails to 7.0.4
  Gemfile
  Gemfile.lock
Labels: hacktoberfest-accepted

#1742 Add PHP dependency parsing
  config/initializers/inflections.rb
  lib/dependency_parser/php/parse.rb
  test/dependency_parsers/php_parser_test.rb
  test/fixtures/files/composer.lock
Labels: hacktoberfest-accepted
